# Generated by Django 5.0 on 2024-01-03 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='phone',
        ),
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='pict',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
